version: "3.9"

services:
  ui:
    image: sagiv:UI
    ports:
      - 3000:3000
  api:
    # image: sagiv:API
    build: ./api
    ports:
      - 8181:8181
    depends_on:
      - db
  db:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "sagiv"
      MONGO_INITDB_ROOT_PASSWORD: "123456"
